package com.animalx.AnimalX.constants;

public enum LogMessage {

	SALVO_COM_SUCESSO,
	ALTERADO_COM_SUCESSO,
	EXCLUIDO_COM_SUCESSO,
	ERRO_AO_SALVAR,
	FALHA_AO_FINALIZAR_OPERACAO,
	OPERACAO_REALIZADA_COM_SUCESSO,
	INFORMACAO_INVALIDA,
}
